#!/bin/bash

sd="/home/jhk/projects/suse/longhorn-website-docusaurus"
for f in "$sd"/blog/*.md "$sd"/kb/*.md
do
  sed -i 's/<=/≤/g' "$f"
  sed -i 's/>=/≥/g' "$f"
  perl -pi -e 's/<(?<url>http[s]{0,1}.*)>/`$+{url}`/g' "$f"
  python /home/jhk/projects/suse/lhws-mig-h2d-tools/tools/fig2img.py "$f"
done

for f in "$sd"/kb/*.md
do
   sed -i 's/](\.\.\/\.\.\/docs\/1\.5\.1/](\.\.\/docs\/1\.5\.1/g' "$f"
   sed -i 's/](\.\.\/troubleshooting/](\.\.\/kb\/troubleshooting/g' "$f"
   perl -pi -e 's/]\((?<before>.*)\/#(?<after>.*?\))/]($+{before}#$+{after}/g' "$f"
done

python /home/jhk/projects/suse/lhws-mig-h2d-tools/tools/i2f_cb.py "$sd"/kb/troubleshooting-unexpected-expansion-leads-to-degradation-or-attach-failure.md
