#!/bin/bash

if [ "$1" == "-wip" ];
then
    shift
    src_path="$HOME/projects/suse/lhws-mig-h2d"
    if [ -d "$src_path"/versioned_docs ]; then
      dirs_to_search="docs versioned_docs"
    else
      dirs_to_search="docs"
    fi
else
    src_path="$HOME/projects/suse/longhorn-website"
    dirs_to_search="content"
fi

function py_pcre_runner {
    local re="$1"
    local ofile="$2"

    cd $src_path || exit 1
    find $dirs_to_search -type f -name '*.md' | while read -r ifile; do
        py_pcre "${re}" "$ifile"
    done > "$ofile"
}

if [ "$1" == "-icb" ]; then
    # shellcheck disable=SC2016
    re='(?:(?:(?:[ \n]*?)(?<fcb>(?:(?:[ \t])*`{3}(?:.|\n)*?`{3})))|(?:^\s$))(*SKIP)(*FAIL)|(?:(?:^\s*\n)(?<icb>^(?:(?:[ ]{4,}|\t)[^`].*?\n|(?:\s))+))'
    ofile="$(realpath outputs/icb.txt)"
    py_pcre_runner "$re" "$ofile"
elif [ "$1" == "-br" ]; then
    re='<br>'
elif [ "$1" == "-egr" ]; then
    re="${2}"
    ofile="$(realpath outputs/egr.txt)"
    cd $src_path || exit 1
    grep -Enr "${re}" --include '*.md' $dirs_to_search > "$ofile"
elif [ "$1" == "-pcre" ]; then
    re="${2}"
    ofile="$(realpath outputs/pcre.txt)"
    cd "$src_path" || exit 1
    pcre2grep -Mnr --include '.*\.md' "${re}" $dirs_to_search > "$ofile"
elif [ "$1" == "-py_pcre" ]; then
    re="${2}"
    ofile="$(realpath outputs/py_pcre.txt)"
    cd "$src_path" || exit 1
    py_pcre_runner "$re" "$ofile"
else
    echo "provide an option"
    exit 1
fi
