#!/bin/bash

function py_pcre_runner {
    local re="$1"
    local ofile="$2"

    cd ~/projects/suse/longhorn-website || exit 1
    find content -type f -name '*.md' | while read -r ifile; do
        py_pcre "${re}" "$ifile"
    done > "$ofile"
}

if [ "$1" == "-icb" ]; then
    # shellcheck disable=SC2016
    re='(?:(?:(?:[ \n]*?)(?<fcb>(?:(?:[ \t])*`{3}(?:.|\n)*?`{3})))|(?:^\s$))(*SKIP)(*FAIL)|(?:(?:^\s*\n)(?<icb>^(?:(?:[ ]{4,}|\t)[^`].*?\n|(?:\s))+))'
    ofile="$(realpath outputs/icb.txt)"
    py_pcre_runner "$re" "$ofile"
elif [ "$1" == "-br" ]; then
    re=''
elif [ "$1" == "-egr" ]; then
    re="${2}"
    ofile="$(realpath outputs/egr.txt)"
    cd ~/projects/suse/longhorn-website || exit 1
    grep -Enr "${re}" --include '*.md' content > "$ofile"
else
    echo "provide an option"
    exit 1
fi
